#!/bin/bash
export BLUE='\033[1;94m'
export RED='\033[1;91m'
export GREEN='\033[1;92m'
export YELLOW='\033[1;33m'
export RESETCOLOR='\033[1;00m'

dep_test() {
# test_convert=$(which convert 2>/dev/null)
test_wrestool=$(which wrestool 2>/dev/null)
# if [ -z $test_convert ]
#     then
#         echo -en "${RED}\n  !!!You must install imagemagick to continue!!!\n\n$RESETCOLOR" >&2
#         exit 1
# fi
if [ -z $test_wrestool ]
    then
        echo -en "${RED}\n  !!!You must install icoutils to continue!!!\n\n$RESETCOLOR" >&2
        exit 1
fi
}

exe2png_help() {
echo -e "
        ${RED} PNG icon generator from EXE files
            ${RED}Usage:
            $RED┌──[$GREEN$USER$YELLOW@$BLUE`uname -a|awk '{print$2}'`$RED]─[$GREEN$PWD$RED]
            $RED└──╼ \$$GREEN"" exe2png ${RED}blabla.exe
        $RESETCOLOR" >&2
        exit 1
}

exe2png_run() {
cd "$( dirname "$1")"
wrestool -x --output=./ -t14 "$1" 2>/dev/null
if ! [ -z $(ls *.ico 2>/dev/null|head -1) ]
    then
        (IFS=$'\n' ; for i in $(ls *.ico 2>/dev/null)
                        do
                        echo -en "${GREEN}Found ${RED}"$i" ${GREEN}and converting to PNG...\n$RESETCOLOR" >&2
                        icotool -x --output=./ "$i" 2>/dev/null
                        #convert "$i" $(echo "$i"|cut -d'.' -f1).png 2>/dev/null
                    done)
        echo -en "${RED}$(ls *.png 2>/dev/null)\n$RESETCOLOR" >&2
        echo -en "${YELLOW}CLEANUP...\n"
        rm -rf *.ico
        echo -en "${BLUE}ALL DONE!\n$RESETCOLOR" >&2
    else
        echo -en "${RED}ICO not found\n$RESETCOLOR" >&2
        exit 1
fi
}

dep_test

if ! [ -z "$1" ]
    then
        if [ "$1" == "--help" ]
            then
                exe2png_help
        fi
        if [ -f "$1" ]
           then
                exe2png_run "$1"
           else
                exe2png_help
        fi
    else
        exe2png_help
fi
